# =================================================================
# apps/learning/api/urls.py
# -----------------------------------------------------------------
# KEEPS THE SYSTEM INTEGRATED: This file provides the API endpoints
# for the core learning content, allowing programmatic access to
# courses and learning paths as required by the foundational docs.
# =================================================================

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CourseViewSet, LearningPathViewSet

# A router is used to automatically generate the URL patterns for a ViewSet.
# This is the standard and most professional way to build DRF APIs.
router = DefaultRouter()
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'paths', LearningPathViewSet, basename='learning-path')

# The main urlpatterns for this app's API.
# It simply includes all the URLs generated by the router.
urlpatterns = [
    path('', include(router.urls)),
]